### ISSUE TITLE
Fix mac builds on Travis

### ISSUE THREAD

**Issue by Dekken** [X-DataInitiative/tick#141]
Since this weekend something has changed to result in travis builds failing within the "travis" part of the code. We don't have access to this so the only real solution is to add

```
set +e
```

**Comment by Dekken** [comment]
Also pyenv upgrade is failing

**Comment by Mbompr** [comment]
Will travis job still fail if we have an error with cpptest / doc / cpplint / python tests ?

**Comment by stephanegaiffas** [comment]
That’s be annoying if not :(


Le 4 décembre 2017 à 13:13:27, Martin (notifications@github.com) a écrit:

Will travis job still fail if we have an error with cpptest / doc / cpplint
/ python tests ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/X-DataInitiative/tick/issues/141#issuecomment-348945299>,
or mute the thread
