### ISSUE TITLE
Add weights in models

### ISSUE THREAD

**Issue by stephanegaiffas** [X-DataInitiative/tick#161]
Add weights for all generalized linear models, and for cox regression.

**Comment by sebconort** [comment]
Hello. 
Would like to help on that one, at least for poisson regression as random time exposure is a frequent use case. 
Though would need some guidance on all files to be updated

**Comment by stephanegaiffas** [comment]
Cool ! There is a bunch of files to update for this, basically all the files about linear models.
It starts with the base_model folders (in swig, include and cpp), then the files in linear_model (again, swig, include and cpp) and the python model files (base_model and linear_model). That's a bunch of files to change, but I think that this is not difficult.

**Comment by Mbompr** [comment]
As this issue is quite old, can we redefine what we were looking for? To me I would say the goal is to take into account some weights a_i such that the loss function L(w) write (in the case of general linear models) :
<img src="https://user-images.githubusercontent.com/1908833/53697915-7e228d00-3dd6-11e9-985c-1f3071b3aa65.png" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200"  />
where w are the weights of the models, y_i the labels and x_i the observations.

In this case, what should be done would be adding an optional `weight` vector to the general linear [ModelGeneralizedLinear](https://github.com/X-DataInitiative/tick/blob/master/lib/include/tick/base_model/model_generalized_linear.h) class, that would be called to reweight the `loss_i` and `grad_i` functions.

**Comment by Dekken** [comment]
a "with weights" class would be preferred at runtime IMO

**Comment by sebconort** [comment]
@Mbompr exactly, thats the goal.

To be honest, i am not really experienced in C++, and I am much more experienced in Python.

I tried to compile tick on my machine, but still gets error...

I thought maybe adding weights in Python classes would be easy and enough if the grad_i and loss_i methods would be made available in python objects, and they are not. 
The idea would be to 'numpy vectorised version' of the grad_i and loss_i methods, and do the weighted average.

Also, regarding the Poisson with exponential link function (which is the most handicaped model without weights), how to impact the dual problems with weights?

Thanks

**Comment by Dekken** [comment]
feel free to join us @ https://gitter.im/xdata-tick/Lobby and we can try solve you compile error

**Comment by stephanegaiffas** [comment]
Would like to reopen this, any ideas
