### ISSUE TITLE
Math question regarding parametric estimation of Hawkes processes

### ISSUE THREAD

**Issue by chenzhigu** [X-DataInitiative/tick#270]
Hi,
First I want to thank you for making estimation much easier.

I have one (math) question on the parametric estimation of Hawkes processes. The four available parametric methods: HawkesExpKern, HawkesSumExpKern, HawkesADM4, HawkesSumGaussians all requires a pre-specified decay, except the last method which assumes Gaussian kernels. I am wondering why the decay cannot be estimated as a parameter but has to be specified. Is it because adjacency and decay parameters can only be jointly identified?

**Comment by Mbompr** [comment]
Hi, 
Indeed they all require a predefined decay because the loss that we will minimize is convex only when the decays are fixed. As a big part of tick relies on convex optimizers it was way simpler to implement these methods.
Also, beyond the optimization that is simpler, these methods have a complexity linearly linked to the number of event. To the best of my knowledge, we would lose this complexity, if we wanted to estimate both decays and adjacency.

**Comment by chenzhigu** [comment]
Martin,
Thanks for the reply now it makes sense.
A few followup questions:

1. Does tick provide any goodness-of-fit measures (such as QQ plot, likelihoods)? If not how would you suggest obtaining any such measures?

2. Do you know any solver packages that treat decay as parameters to be estimated?

Thanks!

**Comment by Mbompr** [comment]
Sorry for the delay,
1. The likelihood can be easily computed with [`ModelHawkesExpKernLogLik`](https://x-datainitiative.github.io/tick/modules/generated/tick.hawkes.ModelHawkesExpKernLogLik.html#tick.hawkes.ModelHawkesExpKernLogLik). The array of parameters simply needs to be flattened. QQ plot can probably be easily obtained too as we can retrieve the [estimated intensity](https://x-datainitiative.github.io/tick/auto_examples/plot_hawkes_estimated_intensity.html).
2. I have not encountered any but I have never actively looked for it.
