### ISSUE TITLE
exponential-powerlaw approximation support?

### ISSUE THREAD

**Issue by crowlogic** [X-DataInitiative/tick#66]
Is the kernel described in https://arxiv.org/abs/1406.3967 supported? the last kernel mentioned on page 3.. its the som of exponentials powerlaw approximation with short-time cutoff

**Comment by Mbompr** [comment]
Hi, I've jumped quickly to your kernel. 
It seems that the kernel you would like to fit is 
<img width="259" alt="screenshot 2017-08-30 08 53 57" src="https://user-images.githubusercontent.com/1908833/29859138-f334b4a6-8d60-11e7-909d-b79c3f53404f.png">
With parametrization
<img width="85" alt="screenshot 2017-08-30 08 54 00" src="https://user-images.githubusercontent.com/1908833/29859149-f9010394-8d60-11e7-8268-ec6afb29db70.png">
so the parameters you need to estimate are b, tau, tau_0 and epsilon?

In _tick_ the only exponential kernels we fit are exponential kernels with fixed decay (named tau / tau_0 here). We do so as this allows us to minimize a convex objective function. To the best of my knowledge, this objective function will not be convex, will it?

**Comment by crowlogic** [comment]
thanks-! correct, it is not convex. maybe if the tau param was held
constant?

**Comment by crowlogic** [comment]
I think it can implemented by modifying the sum of exponentials implementation pretty easily.. I'm not really very handy with Python though so I'm trying to implement it in Java/C but thought it would be a nice addition to the tick project and I could check the results/etc

**Comment by crowlogic** [comment]
the parameters are actually 	

{  ρ, b, τ, τ0, ε }; where ρ is the branching rate

**Comment by Mbompr** [comment]
Hi, 
Are you sure that ρ is a parameter you'd like to estimate directly? It rather seems that it can be determined once other parameters { b, τ, τ0, ε } are estimated, isn't it?

Also, if {τ, τ0} are fixed, the loss could be convex indeed and the last parameters that would need to be estimated would be { b, ε } which determine the amplitudes of the exponentials.
Estimating the amplitudes is exactly what our sum of exponentials kernel does. However, it would rather estimate all a_i instead of estimating them through ε. But it should not be too complicated to rewrite the loss as a function of  { b, ε }  and then compute its gradient against these parameters.

Once this loss and gradient are implemented in C++ you can use all the optimization toolbox of tick which could be very useful to fit your parameters. 

If you're interested it would be a pleasure to help you implement it in tick but I won't have time to implement it myself in a near future.

**Comment by crowlogic** [comment]
rho is the branching rate which can be estimates thru other parameters..
but if the process is long memory with finite mean and variance then rho is
necessarily equal to 1. tau and tau0 will need to be estimated.. for the
parameters which are not convex there can be a brute force line/grid search
across a set of optimizations.. I will looki to it and see if i can re-use
the code.. are there any tutorials? i noticed the documentarion links were
all messed up and not rendering.. i wanna run thru a few known cases before
i start hacking

**Comment by crowlogic** [comment]
I've got this implemented in my person Java/C project.. it hurts my brain to code in  loosely typed languages so I don't think I'll have the wherewithal to implement this for the tick project.. as cool as a project as it is
